<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or enter a US zip code_GLUXZipUpdateInput</name>
   <tag></tag>
   <elementGuidId>bb340a93-98a2-4143-bee1-6385e638552f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GLUXZipUpdateInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GLUXZipUpdateInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7aa18bf-267e-4c5f-9006-a556d72f3209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GLUX_Full_Width a-declarative</value>
      <webElementGuid>af8f9f56-8f85-430d-ae4c-59b6caaf2211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>734ac69c-dfe1-4bf6-9638-3bf19cec1152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>59d750da-630a-4919-9ec5-db134a389f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GLUXZipUpdateInput</value>
      <webElementGuid>ab780369-c7cf-42b3-b9a7-52def7882b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>or enter a US zip code</value>
      <webElementGuid>7c5988bc-8822-4d2a-b63f-793d0b6adca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>GLUXPostalInputAction</value>
      <webElementGuid>1e381941-795f-448a-9b5c-af61b67fc2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GLUXZipUpdateInput&quot;)</value>
      <webElementGuid>cf67b766-b4d4-477f-869a-cbc885c0f576</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GLUXZipUpdateInput']</value>
      <webElementGuid>e64ce802-1d17-48ad-8ed8-516221da1ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GLUXZipInputSection']/div/input</value>
      <webElementGuid>faf60d57-3550-4f6f-8475-4bf6e9bc92c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>23a08e01-1164-48ce-9e2b-69258f53d74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'GLUXZipUpdateInput']</value>
      <webElementGuid>9208f758-82f4-4f3a-8e9d-6c114f2e9fe2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
