<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_India</name>
   <tag></tag>
   <elementGuidId>9220a7f3-5188-4f8b-b62b-a3263c0660d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#glow-ingress-line2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='glow-ingress-line2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>98e39f40-ff32-4019-ae86-03246379dc61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-line-2 nav-progressive-content</value>
      <webElementGuid>d8104d7d-54b9-43af-90bb-a2e7293f2115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>glow-ingress-line2</value>
      <webElementGuid>7b6c6a1a-af71-422f-96b2-f7a81d9046b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                   India
                </value>
      <webElementGuid>b71dfb58-d216-48d6-ab3b-60ece664fa74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;glow-ingress-line2&quot;)</value>
      <webElementGuid>2574b520-5fd6-4187-9afe-ee97f6444d16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='glow-ingress-line2']</value>
      <webElementGuid>31432cd9-b075-4fae-86b4-1e46c7fde39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='glow-ingress-block']/span[2]</value>
      <webElementGuid>220f3f1c-6c8a-4063-b1a7-f3f6100be2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>0bc89f1a-0a17-4adc-80df-a01ed4fdee99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'glow-ingress-line2' and (text() = '
                   India
                ' or . = '
                   India
                ')]</value>
      <webElementGuid>a9279030-8a13-4b55-9896-ef61639609ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
