<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_- INR - Indian Rupee</name>
   <tag></tag>
   <elementGuidId>683fc237-0202-44a1-beea-576c6becdae3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icp-currency-dropdown_44</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='icp-currency-dropdown_44']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>57469e5b-004e-4ced-8ad4-b4811b4347ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d69ab86d-dd0f-423f-8cf9-54033d8f5caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>f222a379-2aab-4118-9b24-c23b0140f04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4fe28e1b-4075-460d-a7d4-96361c8ab281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;INR&quot;}</value>
      <webElementGuid>3769daa6-425e-42db-9dae-3e4c8dd793b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icp-currency-dropdown_44</value>
      <webElementGuid>fe169a8b-982c-49dc-9ed9-836946814191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link a-active</value>
      <webElementGuid>ae2536f8-03c7-4118-8a96-c517f8f3c815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>₹ - INR - Indian Rupee</value>
      <webElementGuid>9ebba15e-2353-4afb-93a3-52789dc2d9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icp-currency-dropdown_44&quot;)</value>
      <webElementGuid>4401b449-36c8-4466-85ee-48e43ea6789a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='icp-currency-dropdown_44']</value>
      <webElementGuid>3f581ce5-cb02-4db4-934b-3c692e7424a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='INR']/a</value>
      <webElementGuid>056ecf00-7966-4116-8223-cc0cb2fe6c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[46]</value>
      <webElementGuid>c06f0e8b-b2a6-4c64-a401-e9f63caa33db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[46]/a</value>
      <webElementGuid>31020f35-7950-4c17-9a7e-eaebf2a6aa48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'icp-currency-dropdown_44' and (text() = '₹ - INR - Indian Rupee' or . = '₹ - INR - Indian Rupee')]</value>
      <webElementGuid>57db2c1a-135a-4cd5-be4c-172c9912df6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
